<a href="https://colab.research.google.com/github/kaushal1017/Data-Analytics-Assignments/blob/main/Assignment2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.) Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print()
print(type(arr))

[1 2 3 4 5]

<class 'numpy.ndarray'>


## 2.) Given a NumPy array 'arr', check if its data type is float64.


  - arr = np.array([1.5, 2.6, 3.7])

In [ ]:
import numpy as np
arr = np.array([1.5, 2.6, 3.7])
print(arr)
print("Datatype: ",arr.dtype)

[1.5 2.6 3.7]
Datatype:  float64


## 3.) Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [ ]:
import numpy as np
arr = np.array([1+5j,2+5j,3+4j])
print(arr)
print("Datatype: ",arr.dtype)

[1.+5.j 2.+5.j 3.+4.j]
Datatype:  complex128


## 4.) Convert an existing NumPy array 'arr' of integers to float32 data type.

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print("Orignal array:", arr)
print("orignal type:",type(arr))

ar_float = arr.astype(np.float32)
print("final array:",ar_float)
print("final type:",ar_float.dtype)

Orignal array: [1 2 3 4 5]
orignal type: <class 'numpy.ndarray'>
final array: [1. 2. 3. 4. 5.]
final type: float32


## 5.) Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [ ]:
import numpy as np

arr = np.array([2.3,3.2,4.5],dtype= "float64")
print("Orignal array:", arr)
print("orignal type:",arr.dtype)

ar_float = arr.astype(np.float32)
print("final array:",ar_float)
print("final type:",ar_float.dtype)

Orignal array: [2.3 3.2 4.5]
orignal type: float64
final array: [2.3 3.2 4.5]
final type: float32


## 6.) Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type?



In [ ]:
def array_attributes(ar1):
  print("Array:",ar1)
  print("array shape =",ar1.shape)
  print("array size =",ar1.size)
  print("array type =",ar1.dtype)


ar1 = np.array([10,20,30,40,50])
array_attributes(ar1)

Array: [10 20 30 40 50]
array shape = (5,)
array size = 5
array type = int64


## 7.) Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [ ]:
def array_dimension(ar2):
  print("Array:",ar2)
  return ar2.ndim


ar2 = np.array([10,20,30])
print("Dimension:",array_dimension(ar2))
print()
ar2 = np.array([[10,20],[30,40]])
print("Dimension:",array_dimension(ar2))
print()
ar2 = np.array([[[10,20,30]]])
print("Dimension:",array_dimension(ar2))

Array: [10 20 30]
Dimension: 1

Array: [[10 20]
 [30 40]]
Dimension: 2

Array: [[[10 20 30]]]
Dimension: 3


## 8.) Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [ ]:
def item_size_info(ar1):

  print("given array:",ar1)
  print("Item size of given array:-",ar1.itemsize)
  print("Total memory size of given array:-", "%d bytes"%(ar1.size * ar1.itemsize))


ar1 = np.array([10,20,30,40,50])
item_size_info(ar1)


given array: [10 20 30 40 50]
Item size of given array:- 8
Total memory size of given array:- 40 bytes


## 9.) Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [ ]:
import numpy as np

def array_stride(ar1):
  return ar1.stride

ar1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(array_stride(ar1))


## 10.) Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array

In [ ]:
def shape_stride_relationship(arr1):
  return arr1.shape, arr1.strides

arr1 = np.array([[1,2,3],[4,5,6]])
print(shape_stride_relationship(arr1))

((2, 3), (24, 8))


NOTE : The strides of an array tell us how many bytes we have to skip in memory to move to the next position along a certain axis.

## 11.) Create a function create_zeros_array that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements

In [ ]:
import numpy as np

def create_zeros_array(n):
  ar = np.zeros(n)
  return ar

create_zeros_array(5)

array([0., 0., 0., 0., 0.])

## 12.) Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`

In [ ]:
import numpy as np
def create_ones_matrix(m,n):
  ar_ones = np.ones((3,5))
  return ar_ones

create_ones_matrix(3,4)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## 13.) Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

In [ ]:
import numpy as np

def generate_range_array(p,q,r):
# input arguement p = start, q = stop, r = step

  ar = np.arange(p,q,r)
  return ar

generate_range_array(10,30,3)


array([10, 13, 16, 19, 22, 25, 28])

## 14.) Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

In [ ]:
import numpy as np
def generate_linear_space(p,q,n):
  ar = np.linspace(p,q,n)
  return ar

generate_linear_space(1,30,10)


array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])

## 15.) Create a function`create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using`numpy.eye`.

In [ ]:
import numpy as np

def create_identity_matrix(n):
  ar = np.eye(n)
  return ar

create_identity_matrix(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## 16.) Write a function that takes a Python list and converts it into a NumPy array.

In [ ]:
import numpy as np

def list_into_array(list1):
  ar = np.array(list1)
  return ar

list1= [10,20,30,40,50]
list_into_array(list1)

array([10, 20, 30, 40, 50])

## 17.) Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [ ]:
import numpy as np
ar1 = np.array([10,20,30,40])
print("first array: ",ar1,type(ar1))
ar2 = ar1.view()
print("second array: ",ar2,type(ar2))


first array:  [10 20 30 40] <class 'numpy.ndarray'>
second array:  [10 20 30 40] <class 'numpy.ndarray'>


## 18.) Write a function that takes two NumPy arrays and concatenates them along a specified axis

In [ ]:
import numpy as np

def concat_2ar(x,y):
  return np.concatenate([x,y])

x = np.array([10,20,30])
y = np.array([40,50])
concat_2ar(x,y)


array([10, 20, 30, 40, 50])

## 19.) Create two NumPy arrays with different shapes and concatenate them horizontally .

In [ ]:
import numpy as np

def concat_hz(x,y):
  return np.concatenate([x,y],axis =1)

x = np.array([[1,2],[3,4]])
y = np.array([[1,2,3],[3,4,2]])

concat_hz(x,y)

array([[1, 2, 1, 2, 3],
       [3, 4, 3, 4, 2]])

## 20.) Write a function that vertically stacks multiple NumPy arrays given as a list

In [ ]:
import numpy as np

def ver_stack(x,y):
  return np.vstack((x,y))


x = np.array([3, 5, 7])
y = np.array([5, 7, 9])
ver_stack(x,y)

array([[3, 5, 7],
       [5, 7, 9]])

## 21.) Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [ ]:
import numpy as np
def array_in_range(l,u,s):
  return np.arange(l,u+1,s)

array_in_range(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

## 22.) Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [ ]:
import numpy as np

def array_equally_spaced(l,u,num):
  return np.linspace(l,u,num)

array_equally_spaced(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## 23.) Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [ ]:
import numpy as np

def log_spaced_value(l,u,num):
  return np.logspace(l,u,num)

log_spaced_value(1,1000,5)

array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

## 24.) Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

In [ ]:
import numpy as np
import pandas as pd

ar = np.random.randint(100,size= (5,3))
df = pd.DataFrame(ar)
df



0   1   2
0   2  20  15
1  73  86  32
2  81  66  63
3  52  61  38
4  58  40   9

## 25.) Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame

In [ ]:
import pandas as pd

df = pd.DataFrame({"A": [1, 2, -3, 4, -5, 6],
                   "B": [3, -5, -6, 7, 3, -2],
                   "C": [-4, 5, 6, -7, 5, 4]})

print("Original Array : ")
print(df)

df[df < 0] = 0
print("\nNew Array :")
df

Original Array : 
   A  B  C
0  1  3 -4
1  2 -5  5
2 -3 -6  6
3  4  7 -7
4 -5  3  5
5  6 -2  4

New Array :


A  B  C
0  1  3  0
1  2  0  5
2  0  0  6
3  4  7  0
4  0  3  5
5  6  0  4

## 26.) Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


## 27.) Retrieve the element at index (1, 2) from the 2D NumPy array.

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1][2])

6


## 28.) Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

In [ ]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])
new_arr = arr[arr>5]
print(new_arr)

[ 8 10  7]


## 29.) Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_subset = arr[2:6]
print(arr_subset)

[3 4 5 6]


## 30.) Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
import numpy as np

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Orignal Array:-")
print(arr_2d)

subarray = arr_2d[:2,1:]
print("\nSub_array:-")
print(subarray)

Orignal Array:-
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sub_array:-
[[2 3]
 [5 6]]


## 31.) Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [ ]:
import numpy as np
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

arr2= np.arange(1,9).reshape(4,2)
arr2_indices = np.where(arr2)
print(arr2_indices)

arr3 = arr1[arr2_indices].reshape(4,2)
print(arr3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(array([0, 0, 1, 1, 2, 2, 3, 3]), array([0, 1, 0, 1, 0, 1, 0, 1]))
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


## 32.) Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

In [ ]:
import numpy as np
def greater_element(x,n):
  x_new = x[x>n]
  return x_new

x = np.array([5,7,8,9,4,6,5,10,1,12,2])
greater_element(x,9)

array([10, 12])

## 33.) Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

In [ ]:
import numpy as np
ar_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(ar_3d)
print("Dimension of array:",ar_3d.ndim)
print("shape:",ar_3d.shape)

# Extract 6  from above 3d array
print("extracted element:",ar_3d[1,0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension of array: 3
shape: (2, 2, 2)
extracted element: 6


## 34.) Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

In [ ]:
import numpy as np
x = np.array([3,4,7,8,9,10,15,18,20])
mask1 = x>5
mask2 = x<10
print(x[mask1 & mask2])


[7 8 9]


## 35.) Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [ ]:
import numpy as np
ar1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

ar2 = np.array([[1,2],[3,4]])

mask = np.where(ar2)
result = ar1[mask]

print(result)

[1 2 4 5]


## 36.) Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr_new = arr + 5
print(arr_new)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## 37.) Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [ ]:
import numpy as np
ar1 = np.array([1,2,3])
ar2 = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
result = ar2*ar1.reshape(3,1)
print(result)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]]


## 38.) Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [ ]:
import numpy as np
ar1 = np.array([10,20,30,40])
ar2 = np.array([[1,2,3],
                [5,6,7],
                [9,10,11],
                [13,14,15]])
result = ar2 + ar1.reshape(4,1)
print(result)

[[11 12 13]
 [25 26 27]
 [39 40 41]
 [53 54 55]]


## 39.) Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [ ]:
import numpy as np
arr1 = np.array([[5],[10],[15]])
arr2 = np.array([[10,20,30]])
add = arr1 + arr2
print(add)

[[15 25 35]
 [20 30 40]
 [25 35 45]]


## 40.) Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [ ]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[1,2]])


# confusion

## 41.) Calculate column wise mean for the given array

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("the mean of given array column wise:-")
print(arr.mean(axis=0))

the mean of given array column wise:-
[2.5 3.5 4.5]


## 42.) Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Maximum value in each rows:")
print(arr.max(axis =1))

Maximum value in each rows:
[3 6]


## 43.) For the given array, find indices of maximum value in each column.

In [ ]:
import numpy as np

arr = np.array([[1, 12, 3], [4, 5, 6]])
print("Indices of maximum value in each column:")
print(arr.argmax(axis =0))

Indices of maximum value in each column:
[1 0 1]


## 44.) For the given array, apply custom function to calculate moving sum along rows.

In [ ]:
import numpy as np
import pandas as pd

arr = np.array([[1, 2, 3], [4, 5, 6]])
df = pd.DataFrame((arr))
df



0  1  2
0  1  2  3
1  4  5  6

## 45.) In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

In [ ]:
import numpy as np
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

result = np.all(arr%2 == 0,axis =0)
result

array([False, False, False])

## 46.) Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

original_array = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
original_array = np.array([1, 2, 3, 4, 5, 6])
new_array = original_array.reshape(3,2)
new_array

array([[1, 2],
       [3, 4],
       [5, 6]])

## 47.) Create a function that takes a matrix as input and returns the flattened array.

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
import numpy as np
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
new_matrix = input_matrix.flatten()
new_matrix

array([1, 2, 3, 4, 5, 6])

## 48.) Write a function that concatenates two given arrays along a specified axis

array2 = np.array([[1,2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

In [ ]:
import numpy as np

array1 = np.array([[1,2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Concat row wise")
print(np.hstack((array1,array2)))

print("Concat column wise")
print(np.vstack((array1,array2)))


Concat row wise
[[1 2 5 6]
 [3 4 7 8]]
Concat column wise
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## 49.) Create a function that splits an array into multiple sub-arrays along a specified axis.

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
import numpy as np

def split_array(original_array,axis):
  result = np.split(original_array, 3, axis=0)
  return result

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
axis =0
split_array(original_array,axis)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

## 50.) Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Orignal array:",arr)

#  insert element
result = np.insert(arr, [2,4],[10,11])
print("After inserting value at a given indices:")
print(result)

# delete element at specified indices
print("remaining elements after deleting 1st and 3rd indices ")
print(np.delete(result, [1, 3]))

Orignal array: [1 2 3 4 5]
After inserting value at a given indices:
[ 1  2 10  3  4 11  5]
remaining elements after deleting 1st and 3rd indices 
[ 1 10  4 11  5]


## 51.) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [ ]:
import numpy as np

arr1 = np.random.randint(1,11,10)
print("arr1:",arr1)

arr2 = np.arange(1,11)
print("arr2:",arr2)
print("\nAfter adding both arrays:-")
add = arr1 + arr2
print("Result:",add)

arr1: [ 6  3  1  1  8  8  9 10  5  8]
arr2: [ 1  2  3  4  5  6  7  8  9 10]

After adding both arrays:-
Result: [ 7  5  4  5 13 14 16 18 14 18]


## 52.) Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise

In [ ]:
import numpy as np

arr1 = np.arange(1,11)
arr1 = arr1[::-1]
print("arr1:",arr1)

arr2 = np.arange(1,11)
print("arr2:",arr2)

result = arr1 - arr2
print("\nAfter substracting arr2 from arr1:-")
print("Result:",result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]

After substracting arr2 from arr1:-
Result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


## 53.) Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [ ]:
import numpy as np

arr1 = np.random.randint(1,6,5)
print("arr1:",arr1)

arr2 = np.arange(1,6)
print("arr2:",arr2)

result = arr1 * arr2
print("\nAfter multiplying both arrays:-")
print("Result:",result)

arr1: [5 1 4 3 3]
arr2: [1 2 3 4 5]

After multiplying both arrays:-
Result: [ 5  2 12 12 15]


## 54.) Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [ ]:
import numpy as np

arr1 = np.arange(2,11,2)
print("arr1:",arr1)

arr2 = np.arange(1,6)
print("arr2:",arr2)

result = arr1 / arr2
print("\nAfter dividing arr1 by arr2:-")
print("Result:",result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]

After dividing arr1 by arr2:-
Result: [2. 2. 2. 2. 2.]


## 55.) Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [ ]:
import numpy as np

arr1 = np.arange(1,6)
print("arr1:",arr1)

arr2 = np.arange(1,6,)
arr2 = arr2[::-1]
print("arr2:",arr2)

result = arr1**arr2
print("\nExponent of arr1 raised to power arr2:-")
print("Result:",result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]

Exponent of arr1 raised to power arr2:-
Result: [ 1 16 27 16  5]


## 56.) Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [ ]:
import numpy as np
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(np.char.count(arr,'hello'))

[1 0 1 0 1]


## 57.) Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [ ]:
import numpy as np

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
for word in arr:
  if word.isupper():
    print(word)

GPT


## 58.) Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
import numpy as geek

arr1 = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(arr1)
arr2= np.char.replace(arr1,'grape','orange')
print (arr2)


['apple' 'banana' 'grape' 'pineapple']
['apple' 'banana' 'orange' 'pineapple']


## 59.) Write a function that concatenates strings in a NumPy array element-wise

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])##

In [ ]:
arr1 = np.array(['Hello', 'World'])
print("arr1:",arr1)

arr2 = np.array(['Open', 'AI'])
print("arr2:",arr2)

result = np.char.add(arr1,arr2)
print("result:",result)

arr1: ['Hello' 'World']
arr2: ['Open' 'AI']
result: ['HelloOpen' 'WorldAI']


## 60.) Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [ ]:
import numpy as np
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def len_longest_string(arr):
  x = max(len(s) for s in arr)
  return x

len_longest_string(arr)



9

## 61.) Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [ ]:
import numpy as np

data = np.random.randint(1,1001,100)
print(data)
print("mean:",data.mean())
print("variance:",data.var())
print("standard deviation:",data.std())

[300 678 768 477 249 939 754 187 184 215 582 101 341 222 291  17 339  42
 772 323 174 709 692 996 282 567  58 943 248  55 497 654 614 910 633 794
 889 525 923 988 283 162 185 875 601 443 775 115 283 175 937 883 504 394
 786 765 623 138 620 330 105 762 568 113 681 896 542 895 453 861  31 788
 185 617 784 944  49 403 796 716 992 177  50 736 251 113 450 838 480 438
 582 203 974 990 148 184 755 216 341 563]
mean: 504.79
variance: 89204.44590000002
standard deviation: 298.6711333557363


## 62.) Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset

In [ ]:
import numpy as np

data = np.random.randint(1,100,50)
print(data)
print("25th percentile",np.percentile(data,25))
print("75th percentile",np.percentile(data,75))

[84 64 98 71 61 67 92 74 85 54  3 39  7 93 82 78 87 76  9 98 45 78 21  7
 82 98 89 84 34 78 62 70 52 42 25 81 83 18 65  7 98 31 81 19 61 52 15 76
 23 86]
25th percentile 35.25
75th percentile 82.75


## 63.) Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [ ]:
import numpy as np
x = np.array([1,3,5,7,9])
y = np.array([2,4,6,8,10])

result = np.corrcoef(x,y)
print(result)

[[1. 1.]
 [1. 1.]]


## 64.) Create two matrices and perform matrix multiplication using NumPy's `dot` function

In [ ]:
import numpy as np

# creating two matrices
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]

result = np.dot(p, q)

print("The matrix multiplication is :")
print(result)

The matrix multiplication is :
[[16 19]
 [26 31]]


## 65.) Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles

In [ ]:
import numpy as np

data = np.random.randint(10,1000,50)
print(data)
print("10th percentile",np.percentile(data,10))
print("10th percentile",np.percentile(data,10))
print("90th percentile",np.percentile(data,90))

[ 52 365 443 632 537 367 855  92 753 469 333  58 190 762  58  92 241 400
  65 399 313 206 393 237 294 756 815 801 541 406 186 706  95 112 103 559
 451 433 287 905 752 281 406 956 911 152 357 156 861 175]
10th percentile 92.0
10th percentile 92.0
90th percentile 819.0


## 66.) Create a NumPy array of integers and find the index of a specific element.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 8, 6, 7, 3, 9, 10])

# display index value of 3
print("All index value of 3 is: ", np.where(a == 3)[0])

print("First index value of 3 is: ",np.where(a==3)[0][0])

All index value of 3 is:  [2 7]
First index value of 3 is:  2


## 67.) Generate a random NumPy array and sort it in ascending order.

In [ ]:
import numpy as np
arr = np.random.randint(1,50,10)
print("Given arrray:",arr)

arr_new = np.sort(arr)
print("Sorted array:",arr_new)



Given arrray: [39 37 33 47 20 35 36 13  2 34]
Sorted array: [ 2 13 20 33 34 35 36 37 39 47]


## 68.) Filter elements > 20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

In [ ]:
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])

filter = arr[arr>20]
print("elements greater than 20 are:",filter)

elements greater than 20 are: [25 42 30]


## 69.) Filter elements which are divisible by 3 from a given NumPy array.

In [ ]:
import numpy as np
arr = np.array([1, 5, 8, 12, 15])

filter = arr[arr%3 == 0]
print("elements divisible by 3 are:",filter)

elements divisible by 3 are: [12 15]


## 70.) Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

mask = (arr>=20) & (arr<= 40)
print("filtered elements  are:", arr[mask])

filtered elements  are: [20 30 40]


## 71.) For the given NumPy array, check its byte order using the `dtype` attribute byteorder

arr = np.array([1, 2, 3])

In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print("Byte order of given array:",arr.dtype.byteorder)

# note: All built-in data-type objects have byteorder either ‘=’ or ‘|’.

Byte order of given array: =


## 72.) For the given NumPy array, perform byte swapping in place using `byteswap()`.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)

print(arr.byteswap(inplace = True))

[16777216 33554432 50331648]


## 73.) For the given NumPy array, swap its byte order without modifying the original array using newbyteorder()`.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.newbyteorder())

[16777216 33554432 50331648]


## 74.) For the given NumPy array and swap its byte order conditionally based on system endianness using newbyteorder()`.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.newbyteorder(">"))
print(arr.newbyteorder("<"))

[16777216 33554432 50331648]
[1 2 3]


## 75.) For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

In [ ]:
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
print(arr.newbyteorder("="))

# CONFUSION

[1 2 3]


### CONFUSION QUES NO 75

## 76.) Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.




In [ ]:
import numpy as np

arr1 = np.arange(1,11)
print("orignal array :",arr1)

copy_arr = arr1.copy()

copy_arr[3] = 100

print("Orignal array after manipulation in copy array:",arr1)
print("Modified copied  array:",copy_arr)

# Comparing the arrays
if np.array_equal(arr1, copy_arr):
    print("Equal")
else:
    print("Not Equal")

orignal array : [ 1  2  3  4  5  6  7  8  9 10]
Orignal array after manipulation in copy array: [ 1  2  3  4  5  6  7  8  9 10]
Modified copied  array: [  1   2   3 100   5   6   7   8   9  10]
Not Equal


## 77.) Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [ ]:
import numpy as np

x = np.random.randint(0,10,9).reshape(3,3)
print("Orignal matrix:-")
print(x)

# extract 2nd row
view_slice = x[1,:]
print("Slice extracted from matrix x:")
print(view_slice)

# manipulation in slice
view_slice[1] = 99

print("Orignal matrix after modification in slice:")
print(x)

Orignal matrix:-
[[8 8 5]
 [3 0 5]
 [7 9 0]]
Slice extracted from matrix x:
[3 0 5]
Orignal matrix after modification in slice:
[[ 8  8  5]
 [ 3 99  5]
 [ 7  9  0]]


## 78.) Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:
import numpy as np

array_a = np.arange(1,13).reshape(4,3)
print("Orignal array:")
print(array_a)

view_b = array_a[1:3,:]
print("Slice extracted from orignal array:")
print(view_b)

view_b = view_b + 5
print("Broadcasting additon of 5 in slice")
print(view_b)
print("Orignal array after modification in slice:")
print(array_a)



Orignal array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Slice extracted from orignal array:
[[4 5 6]
 [7 8 9]]
Broadcasting additon of 5 in slice
[[ 9 10 11]
 [12 13 14]]
Orignal array after modification in slice:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## 79.) Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [ ]:
import numpy as np

orig_array = np.arange(1,9).reshape(2,4)
print("Orignal array:")
print(orig_array)

reshaped_view = orig_array.reshape(4,2).view()
print("Reshaped_view:")
print(reshaped_view)

reshaped_view[(2,0)] = 99
print("Modification in reshaped_view:")
print(reshaped_view)

print("orignal array after modification in reshaped_view")
print(orig_array)

Orignal array:
[[1 2 3 4]
 [5 6 7 8]]
Reshaped_view:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Modification in reshaped_view:
[[ 1  2]
 [ 3  4]
 [99  6]
 [ 7  8]]
orignal array after modification in reshaped_view
[[ 1  2  3  4]
 [99  6  7  8]]


## 80.) Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [ ]:
import numpy as np

data = np.random.randint(1,10,12).reshape(3,4)
print("Orignal data array:")
print(data)

data_copy = data[data>5]
print("extracting element greater than 5 :")
print(data_copy)

print("Modify an element in data_copy:")
data_copy[1] = 100
print(data_copy)

print("data array after modification in extracted copy")
print(data)


Orignal data array:
[[2 1 6 7]
 [7 3 7 1]
 [3 3 7 6]]
extracting element greater than 5 :
[6 7 7 7 7 6]
Modify an element in data_copy:
[  6 100   7   7   7   6]
data array after modification in extracted copy
[[2 1 6 7]
 [7 3 7 1]
 [3 3 7 6]]


## 81.) Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [ ]:
import numpy as np
A = np.arange(1,5).reshape(2,2)
print("matrix A:")
print(A)

B = np.arange(1,5).reshape(2,2)
print("\nmatrix B:")
print(B)

add = A + B
sub = A - B

print("\nResult of matrix addition:")
print(add)
print("\nResult of matrix substraction:")
print(sub)

matrix A:
[[1 2]
 [3 4]]

matrix B:
[[1 2]
 [3 4]]

Result of matrix addition:
[[2 4]
 [6 8]]

Result of matrix substraction:
[[0 0]
 [0 0]]


## 82.) Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [ ]:
import numpy as np
C = np.arange(0,6).reshape(3,2)
print("matrix C:")
print(C)

D = np.arange(0,8).reshape(2,4)
print("\nmatrix D:")
print(D)

result = C.dot(D)
print("\nResult of matrix multiplication:")
print(result)


matrix C:
[[0 1]
 [2 3]
 [4 5]]

matrix D:
[[0 1 2 3]
 [4 5 6 7]]

Result of matrix multiplication:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


## 83.) Create a matrix `E` and find its transpose.

In [ ]:
import numpy as np
E = np.arange(0,6).reshape(3,2)
print("matrix E:")
print(E)

print("Transpose of matrix E:")
print(np.transpose(E))

matrix E:
[[0 1]
 [2 3]
 [4 5]]
Transpose of matrix E:
[[0 2 4]
 [1 3 5]]


## 84.) Generate a square matrix `F` and compute its determinant.

In [ ]:
import numpy as np
F = np.arange(1,10).reshape(3,3)
print("matrix F:")
print(F)

print("Determinant of matrix F:")
print(np.linalg.det(F))

matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of matrix F:
0.0


## 85.) Create a square matrix `G` and find its inverse.

In [ ]:
import numpy as np
G = np.arange(1,5).reshape(2,2)
print("matrix G:")
print(G)

print("Inverse of matrix G:")
print(np.linalg.inv(G))

matrix G:
[[1 2]
 [3 4]]
Inverse of matrix G:
[[-2.   1. ]
 [ 1.5 -0.5]]
